version: '3.8'

services:
  frontend:
    image: 981498564176.dkr.ecr.eu-north-1.amazonaws.com/my-frontend-app:latest
    ports:
      - "80:80"
    restart: always
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000/api/
  backend:
    image: 981498564176.dkr.ecr.eu-north-1.amazonaws.com/my-backend-app:latest
    ports:
      - "8000:8000"
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      DJANGO_SECRET_KEY: "o26-xOn1PjQkX7GRTPNhZQfeqU07NYpEua8PtoJ_hICCQRvE9GN6v4vsAi6sUOh4grY"
      DJANGO_ALLOWED_HOSTS: "*"
      DJANGO_DEBUG: "False"
    
    depends_on:
      db:
        condition: service_healthy
    restart: always
 
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-u","root","-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
volumes:
  db_data:


