name: CI/CD pipeline for AWS EC2

on:
  push:
    branches:
      - main 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout my-project-infra repository
        uses: actions/checkout@v4
        with:
          repository: M7MDX69/my-project-infra
          path: my-project-infra
          
      - name: Checkout my-frontend-app repository
        uses: actions/checkout@v4
        with:
          repository: M7MDX69/my-frontend-app
          path: my-frontend-app
          
      - name: Checkout my-backend-app repository
        uses: actions/checkout@v4
        with:
          repository: M7MDX69/my-backend-app
          path: my-backend-app
          
      - name:  configure Aws Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to amazon ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      #build and push image to ecr
      - name: build and push front to ecr
        env: 
          REACT_APP_BACKEND_URL: http://${{ secrets.EC2_HOST }}:8000/api/
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          cd my-frontend-app 
          docker buildx build --platform linux/amd64 \
            --build-arg REACT_APP_BACKEND_URL="${REACT_APP_BACKEND_URL}" \
            -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/my-frontend-app:latest \
            --no-cache --force-rm --push . 
          cd ..

      - name: build and push backend to ecr
        env: 
          REACT_APP_BACKEND_URL: http://${{ secrets.EC2_HOST }}:8000/api/
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          cd my-backend-app && \
          docker buildx build --platform linux/amd64 \
            --build-arg REACT_APP_BACKEND_URL="${REACT_APP_BACKEND_URL}" \
            -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/my-backend-app:latest \
            --no-cache --force-rm --push . &&\
          cd ..

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
                  cd ~/my-project-infra 
                  git pull origin main
                  aws ecr get-login-password --region ${{secrets.AWS_REGION}} | docker login --username AWS --password-stdin ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{secrets.AWS_REGION}}.amazonaws.com
                  docker compose down 
                  docker compose pull
                  docker compose up -d
                  sleep 10
                  BACKEND_CONTAINER_ID=$(docker ps -aqf "name=my-project-infra-backend-1")
                  docker exec $BACKEND_CONTAINER_ID python manage.py migrate
                  echo "Deployment complete!"
                    
                    
            
            

          
         
      
        
          
